CREATE DATABASE ATV_15

USE ATV_15

set language Brazilian

CREATE OR ALTER FUNCTION dbo.SF_DataCompleta(@DATA DATE)
RETURNS VARCHAR(100)
AS
BEGIN
	RETURN LTRIM(STR(DAY(@DATA))) + ' de ' + LTRIM(DATENAME(mm, @DATA)) + ' de ' + LTRIM(STR(YEAR(@DATA)))
END

DECLARE @DATE VARCHAR(100)
EXEC @DATE = dbo.Sf_DataCompleta '2023-07-31'
PRINT @DATE