DROP TABLE IF EXISTS TB_VENDAS
DROP TABLE IF EXISTS TB_FUNCIONARIO
DROP TABLE IF EXISTS TB_CARGO

CREATE DATABASE CTE

USE CTE

CREATE TABLE TB_CARGO (
   CD_CARGO INT NOT NULL PRIMARY KEY,
   CARGO VARCHAR(100) NOT NULL
)

INSERT INTO TB_CARGO VALUES (1, 'DIRETOR'),
                            (2, 'SUPERVISOR'),
    			    (3, 'VENDEDOR')

CREATE TABLE TB_FUNCIONARIO (
   MATRICULA INT NOT NULL PRIMARY KEY,
   NOME VARCHAR(50) NOT NULL,
   CD_CARGO INT NOT NULL REFERENCES TB_CARGO(CD_CARGO),
   MATRICULA_SUPERIOR INT NULL
)

INSERT INTO TB_FUNCIONARIO VALUES(1, 'CARLOS',1,NULL),
                                 (2, 'JOAO',2,1),
				 (3, 'PATRICIA',2,1),
				 (4, 'ROBERTO',3,2),
				 (5, 'PEDRO',3,2),
				 (6, 'MAURICIO',3,3)


CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   MATRICULA INT NOT NULL,
   VALOR NUMERIC(10,2)
)

INSERT INTO TB_VENDAS VALUES(4, 200.00),
                            (4, 100.00),
			    (5, 50.00),
			    (6, 100.00),
			    (6, 500.00),
			    (5, 800.00)

WITH EMP_HIERARQUIA AS
	(SELECT MATRICULA, MATRICULA_SUPERIOR, NOME
	FROM TB_FUNCIONARIO WHERE NOME = 'CARLOS'
	UNION ALL
	SELECT F.MATRICULA, F.MATRICULA_SUPERIOR, F.NOME
	FROM EMP_HIERARQUIA H
	INNER JOIN TB_FUNCIONARIO F
	ON (H.MATRICULA = F.MATRICULA_SUPERIOR)
	)
SELECT * FROM EMP_HIERARQUIA