CREATE DATABASE ATV_TG

USE ATV_TG

CREATE TABLE TB_ALUNO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG INT NULL,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE VARCHAR (20) NULL,
)

CREATE TABLE TB_LOG_PENDENCIAS (
  MATRICULA INT,
  NOME VARCHAR(50),
  PENDENCIA VARCHAR(200)
)

CREATE OR ALTER TRIGGER TG_INSERT_ALUNO
ON TB_ALUNO
AFTER INSERT
AS
BEGIN
    DECLARE @MATRICULA INT, @NOME VARCHAR(50), @RG INT, @ENDERECO VARCHAR(100), @TELEFONE VARCHAR(20), @PENDENCIA VARCHAR(200)

    DECLARE C_ALUNO_INSERIDO CURSOR FOR
    SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE FROM INSERTED
    OPEN C_ALUNO_INSERIDO
    FETCH C_ALUNO_INSERIDO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE

    WHILE (@@FETCH_STATUS = 0)
    BEGIN
        IF ISNULL(@RG, '') = ''
        BEGIN
            SET @PENDENCIA = 'FALTA RG'
            INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)
        END

        IF ISNULL(@ENDERECO, '') = ''
        BEGIN
            SET @PENDENCIA = 'FALTA ENDERECO'
            INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)
        END

        IF ISNULL(@TELEFONE, '') = ''
        BEGIN
            SET @PENDENCIA = 'FALTA TELEFONE'
            INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)
        END

        FETCH C_ALUNO_INSERIDO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
    END
    CLOSE C_ALUNO_INSERIDO
    DEALLOCATE C_ALUNO_INSERIDO
END


-- Inserindo valores na tabela TB_ALUNO
INSERT INTO TB_ALUNO (MATRICULA, NOME, RG, ENDERECO, TELEFONE)
VALUES
    (1, 'João Silva', NULL, 'Rua A, 123', '123-456-7890'),
    (2, 'Maria Santos', 987654, NULL, '987-654-3210'),
    (3, 'Pedro Oliveira', NULL, NULL, NULL),
    (4, 'Ana Souza', 123456, 'Avenida B, 456', NULL);

select * from TB_ALUNO
select * from TB_LOG_PENDENCIAS
