CREATE DATABASE PS_10

USE PS_10

CREATE TABLE TB_CLIENTE (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

CREATE TABLE TB_VENDAS (
   CD_VENDA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
   DT_VENDA DATETIME NOT NULL,
   CD_CLIENTE INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   QUANTIDADE INT NOT NULL,
   VALOR_TOTAL NUMERIC(10,2) NOT NULL
)


CREATE TABLE TB_CLIENTE_ALVO (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

CREATE TABLE TB_CLIENTE_PARCEIRO (
  CD_CLIENTE INT NOT NULL PRIMARY KEY,
  NM_CLIENTE VARCHAR(60) NOT NULL,
  CPF INT NULL,
  DT_INCLUSAO DATETIME NOT NULL
)

CREATE OR ALTER PROCEDURE SP_CLASSIFICA_CLIENTE (@DATA DATETIME, @QTD_PRODUTO INT, @STATUS VARCHAR(50) OUTPUT) AS
	IF @DATA > '2018-03-01' OR @QTD_PRODUTO > 50
		SET @STATUS = 'PARCEIRO'

	ELSE
		SET @STATUS = 'ALVO'

DECLARE @STATUS VARCHAR(50)
EXEC SP_CLASSIFICA_CLIENTE '2017-08-25', 20, @STATUS OUTPUT
SELECT @STATUS

---------------------------------------------------------------------------------------------------------------------

-- Inserts para a tabela TB_CLIENTE
INSERT INTO TB_CLIENTE (CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO)
VALUES
  (1, 'João da Silva', 1234, '2023-07-20 10:00:00'),
  (2, 'Maria Oliveira', 9876, '2023-07-20 11:30:00'),
  (3, 'Pedro Santos', NULL, '2023-07-20 14:45:00'),
  (4, 'Ana Souza', 9876, '2023-07-20 15:15:00');

-- Inserts para a tabela TB_VENDAS
INSERT INTO TB_VENDAS (DT_VENDA, CD_CLIENTE, CD_PRODUTO, QUANTIDADE, VALOR_TOTAL)
VALUES
  ('2023-07-19 08:00:00', 1, 101, 2, 100.00),
  ('2023-07-19 09:30:00', 2, 102, 1, 50.00),
  ('2023-07-20 12:00:00', 1, 103, 5, 250.00),
  ('2023-07-20 13:30:00', 4, 101, 3, 150.00),
  ('2023-07-20 16:00:00', 3, 103, 1, 50.00);

INSERT INTO TB_CLIENTE
VALUES (5, 'CAIO', 123, '2017-08-25')

INSERT INTO TB_VENDAS
VALUES ('2017-08-25', 5, 6, 20, 1080.00)


CREATE OR ALTER PROCEDURE SP_COPIA_CLIENTE AS
	DECLARE @CD_CLIENTE INT, @QTD_PRODUTO INT, @DATA DATETIME, @STATUS VARCHAR(50)

	DECLARE C_CLIENTE CURSOR FOR
	SELECT C.CD_CLIENTE, C.DT_INCLUSAO, V.QUANTIDADE
	FROM TB_CLIENTE C INNER JOIN TB_VENDAS V
	ON (C.CD_CLIENTE = V.CD_CLIENTE)

	OPEN C_CLIENTE
	FETCH C_CLIENTE INTO @CD_CLIENTE, @DATA, @QTD_PRODUTO

	WHILE (@@FETCH_STATUS = 0)
		BEGIN
			EXEC SP_CLASSIFICA_CLIENTE @DATA, @QTD_PRODUTO, @STATUS OUTPUT

			IF @STATUS = 'PARCEIRO'
				INSERT INTO TB_CLIENTE_PARCEIRO (CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO)
				SELECT CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO
				FROM TB_CLIENTE
				WHERE CD_CLIENTE = @CD_CLIENTE

			ELSE IF @STATUS = 'ALVO'
				INSERT INTO TB_CLIENTE_ALVO (CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO)
				SELECT CD_CLIENTE, NM_CLIENTE, CPF, DT_INCLUSAO
				FROM TB_CLIENTE
				WHERE CD_CLIENTE = @CD_CLIENTE

			FETCH C_CLIENTE INTO @CD_CLIENTE, @DATA, @QTD_PRODUTO
		END
	CLOSE C_CLIENTE
	DEALLOCATE C_CLIENTE

SELECT * FROM TB_CLIENTE
SELECT * FROM TB_CLIENTE_ALVO
SELECT * FROM TB_CLIENTE_PARCEIRO

DELETE FROM TB_CLIENTE_ALVO
DELETE FROM TB_CLIENTE_PARCEIRO

EXEC SP_COPIA_CLIENTE