CREATE DATABASE ATV_TG

USE ATV_TG

CREATE TABLE TB_ALUNO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG INT NULL,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE VARCHAR (20) NULL,
)

CREATE TABLE TB_LOG_PENDENCIAS (
  MATRICULA INT,
  NOME VARCHAR(50),
  PENDENCIA VARCHAR(200)
)

CREATE OR ALTER TRIGGER TG_INSERT_ALUNO
ON TB_ALUNO
AFTER INSERT
AS
BEGIN
	DECLARE	@MATRICULA INT, @NOME VARCHAR(50), @RG INT, @ENDERECO VARCHAR(100), @TELEFONE VARCHAR(20),@PENDENCIA VARCHAR(200)

	DECLARE C_ALUNO_INSERIDO CURSOR FOR
	SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE FROM INSERTED
	OPEN C_ALUNO_INSERIDO
	FETCH C_ALUNO_INSERIDO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE

	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF ISNULL(@RG, 0) = 0
			SET @PENDENCIA = 'FALTA RG'
			INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)
		
		IF ISNULL(@ENDERECO, 0) = 0
			SET @PENDENCIA = 'FALTA ENDERECO'
			INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)

		IF ISNULL(@TELEFONE, 0) = 0
			SET @PENDENCIA = 'FALTA TELEFONE'
			INSERT INTO TB_LOG_PENDENCIAS (MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @PENDENCIA)

		FETCH C_ALUNO_INSERIDO INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	END
CLOSE C_ALUNO_INSERIDO
DEALLOCATE C_ALUNO_INSERIDO