CREATE DATABASE TG_03

USE TG_03

CREATE TABLE TB_FUNCIONARIO (
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SALARIO NUMERIC(10, 2),
	GRATIFICACAO NUMERIC(10, 2)
)

CREATE TABLE TB_LOG_AUMENTO_FUNCIONARIO (
	MATRICULA INT NOT NULL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	DT DATE NOT NULL,
	SALARIO_INTEGRAL_ANTIGO NUMERIC(10, 2) NOT NULL,
	SALARIO_INTEGRAL_NOVO NUMERIC(10,2) NOT NULL
)

CREATE OR ALTER TRIGGER TG_AUMENTO_SALARIO
ON TB_FUNCIONARIO
AFTER UPDATE
AS
BEGIN
	DECLARE @SALARIO_NOVO INT, @GRATIFICACAO_NOVA INT, @SALARIO_VELHO INT, @GRATIFICACAO_VELHA INT
	SET @SALARIO_NOVO = (SELECT SALARIO FROM INSERTED)
	SET @GRATIFICACAO_NOVA = (SELECT GRATIFICACAO FROM INSERTED)
	SET @SALARIO_VELHO = (SELECT SALARIO FROM DELETED)
	SET @GRATIFICACAO_VELHA = (SELECT GRATIFICACAO FROM DELETED)

	IF (@SALARIO_NOVO + @GRATIFICACAO_NOVA) > (@SALARIO_VELHO + @GRATIFICACAO_VELHA)
		INSERT INTO TB_LOG_AUMENTO_FUNCIONARIO (MATRICULA, NOME, DT, SALARIO_INTEGRAL_ANTIGO, SALARIO_INTEGRAL_NOVO)
		VALUES ((SELECT MATRICULA FROM TB_FUNCIONARIO
				 WHERE MATRICULA = (SELECT MATRICULA FROM INSERTED)), 
				 (SELECT NOME FROM TB_FUNCIONARIO
				  WHERE NOME = (SELECT NOME FROM INSERTED)), 
				  GETDATE(), (@SALARIO_VELHO + @GRATIFICACAO_VELHA), (@SALARIO_NOVO + @GRATIFICACAO_NOVA))

	ELSE
		ROLLBACK
END

-- Inserir um funcionário
INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO, GRATIFICACAO)
VALUES (1, 'João Silva', 5000.00, 500.00);

-- Inserir outro funcionário
INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO, GRATIFICACAO)
VALUES (2, 'Maria Souza', 6000.00, 600.00);

-- Inserir mais um funcionário
INSERT INTO TB_FUNCIONARIO (MATRICULA, NOME, SALARIO, GRATIFICACAO)
VALUES (3, 'Pedro Santos', 5500.00, 550.00);

-- Atualizar o salário e a gratificação do funcionário com matrícula 1
UPDATE TB_FUNCIONARIO
SET SALARIO = 6000.00,
    GRATIFICACAO = 600.00
WHERE MATRICULA = 1

-- Atualizar o salário do funcionário com matrícula 1 para 4000.00
UPDATE TB_FUNCIONARIO
SET SALARIO = 4000.00
WHERE MATRICULA = 1
    AND SALARIO > 4000.00;


SELECT * FROM TB_FUNCIONARIO
SELECT * FROM TB_LOG_AUMENTO_FUNCIONARIO