-- A resolução do exercício 2 está em baixo

use bdII_aula01_visoes

DROP TABLE IF EXISTS TB_ALUNO
DROP TABLE IF EXISTS TB_ALUNO2
DROP TABLE IF EXISTS  TB_VENDAS_S02_2018 
DROP TABLE IF EXISTS  TB_VENDAS_S01_2019
DROP TABLE IF EXISTS  TB_VENDAS_S02_2019
DROP TABLE IF EXISTS  TB_VENDAS_S01_2020

-- Sequências

-------------------------------------------------

CREATE TABLE TB_ALUNO (
    CODIGO INT IDENTITY(1,1),
    NOME VARCHAR(50)
)

INSERT INTO TB_ALUNO VALUES('JOSE')
INSERT INTO TB_ALUNO VALUES('CARLOS')

SELECT * FROM TB_ALUNO

--------------------------------------

CREATE TABLE TB_ALUNO2 (
    CODIGO INT ,
    NOME VARCHAR(50)
)

CREATE SEQUENCE SQ_ALUNO START WITH 1  INCREMENT BY 1

INSERT INTO TB_ALUNO2(CODIGO, NOME) VALUES (NEXT VALUE FOR SQ_ALUNO, 'JOSE')

INSERT INTO TB_ALUNO2(CODIGO, NOME) VALUES (NEXT VALUE FOR SQ_ALUNO, 'CARLOS')

SELECT * FROM TB_ALUNO2


-- Visões Particionadas


CREATE SEQUENCE SQ_VENDAS START WITH 1  INCREMENT BY 1

CREATE TABLE TB_VENDAS (
   ID_VENDA INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   CD_FUNCIONARIO INT NOT NULL,
   DT_VENDA DATETIME,
   VL_VENDA NUMERIC(10,2),
   PRIMARY KEY(ID_VENDA)
)

-- Solução

CREATE TABLE TB_VENDAS_S02_2018 (
   ID_VENDA INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   CD_FUNCIONARIO INT NOT NULL,
   DT_VENDA DATETIME CHECK (DT_VENDA >= '20180701' AND -- coluna de particionamento
                            DT_VENDA < '20190101'),
   VL_VENDA NUMERIC(10,2),
   PRIMARY KEY(ID_VENDA, DT_VENDA)
)

CREATE TABLE TB_VENDAS_S01_2019 (
   ID_VENDA INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   CD_FUNCIONARIO INT NOT NULL,
   DT_VENDA DATETIME CHECK (DT_VENDA >= '20190101' AND
                            DT_VENDA < '20190701'),
   VL_VENDA NUMERIC(10,2),
   PRIMARY KEY(ID_VENDA, DT_VENDA)
)

CREATE TABLE TB_VENDAS_S02_2019 (
   ID_VENDA INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   CD_FUNCIONARIO INT NOT NULL,
   DT_VENDA DATETIME CHECK (DT_VENDA >= '20190701' AND
                            DT_VENDA < '20200101'),
   VL_VENDA NUMERIC(10,2),
   PRIMARY KEY(ID_VENDA, DT_VENDA)
)


CREATE VIEW VW_VENDAS
AS
SELECT * FROM TB_VENDAS_S02_2018
UNION ALL
SELECT * FROM TB_VENDAS_S01_2019
UNION ALL
SELECT * FROM TB_VENDAS_S02_2019



-- Testes

INSERT INTO VW_VENDAS (ID_VENDA, CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA, VL_VENDA)
VALUES (NEXT VALUE FOR SQ_VENDAS, 1 ,2 , '20190301', 20.0)

SELECT * FROM TB_VENDAS_S01_2019 

INSERT INTO VW_VENDAS (ID_VENDA, CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA, VL_VENDA)
VALUES (NEXT VALUE FOR SQ_VENDAS, 2 ,4 , '20190901', 50.0)

SELECT * FROM TB_VENDAS_S02_2019 

SELECT * FROM VW_VENDAS

UPDATE VW_VENDAS
SET DT_VENDA = '20180801'
WHERE ID_VENDA = 2

SELECT * FROM TB_VENDAS_S02_2019
      
SELECT * FROM TB_VENDAS_S02_2018 


-- Criação de nova partição

CREATE TABLE TB_VENDAS_S01_2020 (
   ID_VENDA INT NOT NULL,
   CD_PRODUTO INT NOT NULL,
   CD_FUNCIONARIO INT NOT NULL,
   DT_VENDA DATETIME CHECK (DT_VENDA >= '20200101' AND
                            DT_VENDA < '20200701'),
   VL_VENDA NUMERIC(10,2),
   PRIMARY KEY(ID_VENDA, DT_VENDA)
)


ALTER VIEW VW_VENDAS
AS
SELECT * FROM TB_VENDAS_S02_2018
UNION ALL
SELECT * FROM TB_VENDAS_S01_2019
UNION ALL
SELECT * FROM TB_VENDAS_S02_2019
UNION ALL
SELECT * FROM TB_VENDAS_S01_2020



INSERT INTO VW_VENDAS (ID_VENDA, CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA, VL_VENDA)
VALUES (NEXT VALUE FOR SQ_VENDAS, 1 ,2 , '20200101', 20.0)

SELECT * FROM TB_VENDAS_S01_2020

-------------------------------------------------

DROP TABLE IF EXISTS TB_VENDAS_S02_2018
DROP TABLE IF EXISTS TB_VENDAS_S01_2019
DROP TABLE IF EXISTS TB_VENDAS_S02_2019
DROP TABLE IF EXISTS TB_VENDAS_S01_2020

-- Resolução do Exercício 2

CREATE SEQUENCE SQ_VENDAS START WITH 1  INCREMENT BY 1

CREATE TABLE TB_VENDAS(
	ID_VENDA INT NOT NULL PRIMARY KEY,
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME NOT NULL,
	VALOR_VENDA NUMERIC(10, 2) NOT NULL
)

CREATE TABLE TB_VENDAS_S02_2021(
	ID_VENDA INT NOT NULL PRIMARY KEY,
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME CHECK (DT_VENDA >= '20210701' AND
							 DT_VENDA <= '20220101'),
	VALOR_VENDA NUMERIC(10, 2) NOT NULL
)

CREATE TABLE TB_VENDAS_S01_2022(
	ID_VENDA INT NOT NULL PRIMARY KEY,
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME CHECK (DT_VENDA >= '20220101' AND
							 DT_VENDA <= '20220701'),
	VALOR_VENDA NUMERIC(10, 2) NOT NULL
)

CREATE TABLE TB_VENDAS_S02_2022(
	ID_VENDA INT NOT NULL PRIMARY KEY,
	CD_PRODUTO INT NOT NULL,
	CD_FUNCIONARIO INT NOT NULL,
	DT_VENDA DATETIME CHECK (DT_VENDA >= '20220701' AND
							 DT_VENDA <= '20230101'),
	VALOR_VENDA NUMERIC(10, 2) NOT NULL
)

CREATE VIEW VW_VENDAS
AS
SELECT * FROM TB_VENDAS_S02_2021
UNION ALL
SELECT * FROM TB_VENDAS_S01_2022
UNION ALL
SELECT * FROM TB_VENDAS_S02_2022

SELECT * FROM VW_VENDAS

INSERT INTO VW_VENDAS (ID_VENDA, CD_PRODUTO, CD_FUNCIONARIO, DT_VENDA, VALOR_VENDA)
VALUES (NEXT VALUE FOR SQ_VENDAS, 1 ,2 , '20210825', 6500.0)


























