CREATE DATABASE PS_11

USE PS_11

CREATE TABLE TB_USUARIO (
  CD_USUARIO INT NOT NULL PRIMARY KEY,
  NM_USUARIO VARCHAR(60) NOT NULL,
  CPF INT NULL
)

CREATE TABLE TB_LANCAMENTOS (
   CD_LANCAMENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   MES INT NOT NULL,
   ANO INT NOT NULL,
   CD_USUARIO INT NOT NULL,
   TP_LANCAMENTO VARCHAR(1) CHECK (TP_LANCAMENTO IN ('R', 'D')),
   DESCRICAO VARCHAR(200) NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)


CREATE TABLE TB_RESUMO_FINANCEIRO (
   CD_USUARIO INT NOT NULL,
   MES INT NOT NULL,
   ANO INT NOT NULL,
   TOTAL_RECEITAS NUMERIC(10,2) NOT NULL,
   TOTAL_DESPESAS NUMERIC(10,2) NOT NULL,
   PRIMARY KEY(CD_USUARIO, MES, ANO)
)

INSERT INTO TB_USUARIO
VALUES (1, 'JOAO', 51673),
	   (2, 'CARLOS', 43444),
	   (3, 'ROBERTO', 98337)

INSERT INTO TB_LANCAMENTOS
VALUES (1, 2019, 1, 'R', 'CURSO', 100.00),
	   (1, 2019, 1, 'R', 'PALESTRA', 300.00),
	   (1, 2019, 1, 'D', 'COMBUSTÍVEL', 200.00),
	   (4, 2019, 1, 'R', 'CURSO', 400.00),
	   (1, 2019, 2, 'R', 'SEMINÁRIO', 200.00),
	   (1, 2019, 2, 'R', 'PALESTRA', 100.00),
	   (1, 2019, 2, 'D', 'DIÁRIA', 500.00)

CREATE OR ALTER PROCEDURE SP_OBTEM_RESUMO (@CODIGO INT, @MES INT, @ANO INT, @TOTAL_RECEITA NUMERIC(10,2) OUTPUT, @TOTAL_DESPESA NUMERIC(10,2) OUTPUT) AS
	BEGIN
		SET @TOTAL_DESPESA = (SELECT ISNULL(SUM(VALOR), 0)
														FROM TB_LANCAMENTOS
														WHERE MES = @MES AND
															  ANO = @ANO AND
															  TP_LANCAMENTO = 'R' AND
															  CD_USUARIO = @CODIGO)

		SET @TOTAL_RECEITA = (SELECT ISNULL(SUM(VALOR), 0)
														FROM TB_LANCAMENTOS
														WHERE MES = @MES AND
															  ANO = @ANO AND
															  TP_LANCAMENTO = 'D' AND
															  CD_USUARIO = @CODIGO)
	END

DECLARE @TOTAL_RECEITA NUMERIC(10, 2), @TOTAL_DESPESA NUMERIC(10, 2)
EXEC SP_OBTEM_RESUMO 1, 1, 2019, @TOTAL_RECEITA OUTPUT, @TOTAL_DESPESA OUTPUT
SELECT @TOTAL_RECEITA, @TOTAL_DESPESA

--------------------------------------------------------------------------------------

CREATE OR ALTER PROCEDURE SP_INCLUI_RESUMO_FINANCEIRO(@ANO INT) AS
	BEGIN
		DECLARE @CD_USUARIO INT, @MES INT, @TOTAL_RECEITA NUMERIC(10,2), @TOTAL_DESPESA NUMERIC(10,2)

		DECLARE C_USER CURSOR FOR
		SELECT CD_USUARIO FROM TB_USUARIO

		OPEN C_USER
		FETCH C_USER INTO @CD_USUARIO

		WHILE (@@FETCH_STATUS = 0)
			BEGIN
				SET @MES = 1
				WHILE (@MES <= 12)
					BEGIN
						EXEC SP_OBTEM_RESUMO @CD_USUARIO, @MES, @ANO, @TOTAL_RECEITA OUTPUT, @TOTAL_DESPESA OUTPUT
						INSERT INTO TB_RESUMO_FINANCEIRO VALUES(@CD_USUARIO, @MES, @ANO, @TOTAL_RECEITA, @TOTAL_DESPESA)
						SET @MES = @MES + 1
					END
				FETCH C_USER INTO @CD_USUARIO
			END
		CLOSE C_USER
		DEALLOCATE C_USER
	END

SELECT * FROM TB_LANCAMENTOS
SELECT * FROM TB_RESUMO_FINANCEIRO

EXEC SP_INCLUI_RESUMO_FINANCEIRO 2019